#Lab Report: Northeastern Archives and Special Collections

#### Andres Gorbea

## Process Description

In this lab, we went to the Northeastern Archives in the basement of Snell library to examine historical codex and artistic books.  We were seated in the basement where books were already placed in front of our seats.  The book in front of me was the _Dragon Prayer Book_ which was mounted on a platform to preserve its condition as historical books can be fragile.  After having a conversation about our impressions of the books and conclusions drawn upon them, we moved to a different area where artistic books were in showcased.  I was able to observe books like _Boundless_ and _BLOW IT OUT!_ which were alterations of the codex as an expression of art.  After observing the artistic books, we had a conversation about our impressions and observations about these books.

## Observations

I had never gone to the basement level of Snell, so this was exciting from the start.  Once we arrived to the tables, the book in front of me was the _Dragon Prayer Book_, which I didn’t touch initially because I believed it was going to collapse.  After gathering the courage to start handling the book, I realized it was actually was sturdier than I believed it would be.  I found the book to be incredibly beautiful.  It had detailed illustrations on the pages with vibrant colors of orange and blue and indentation on the text was pronounced by a big artistic capital letter to indicate a new paragraph.  I noticed that some of the pages included musical notes in the pages, which made me curious to what this book was about (I had class during the Dragon Prayer Book extra-credit lab).  It also did not have page numbers, which was consistent with the information we had read from previous articles, but it did have tabs popping out of the side of the page of the codex.

The artistic books were mesmerizing.  I had never encountered books that challenge the idea of what a codex means.  I first got to see the Borsuk digital book, which made me question what technology was used, and made me think about the advancement of scanning from a digital camera to a drawing on a page.  I did not think the book was made with code until I read on the back of the book that some words were in Helvetica font but others were in bold Helvetica font, which, for some reason, made me realize that this was code being programmed so that the visual effect was possible.  I found the _Boundless_ book to be incredibly interesting, and quite controversial for some curious reason.  I found artistic books to be a lot of fun to examine.

## Analysis

In James Gleick’s book, _Two wordbooks_, Gleick expresses the notion that when the invention of the dictionary happened, lexicographers emphasized that it would be a tedious and malevolent process that made language ‘hard and inelastic’.  Gleick goes on to highlight the importance of the invention of the dictionary by expressing:
>The dictionary ratifies the persistence of the word. It declares that the meanings of words come from other words. It implies that all words, taken together, form an interlocking structure: interlocking, because all words are defined in terms of other words.

Gleick believes that the definition of the word and the significance of it was defined by the invention of the dictionary, as I believe that the incorporation of art into books such as maps in geography books, as observed in the lab, shaped the definition of geography itself.  People would not have been able to comprehend the grandiosity and complexity of the map of Earth if maps weren’t incorporated into such books.  Last week we were able to examine a geography book without maps in them, which almost didn’t make sense to describe the world using words if maps weren’t existent.  It would be useless to use words to describe a map as it would be useless to use words without a dictionary.

In Bonnie Mak’s article, _Architectures of the Page_, Mak describes the page as 
>The page is thus an interface, standing at the centre of the complicated dynamic of intention and reception; it is the material mani- festation of an ongoing conversation between designer and reader.
This notion expressed by Mak was challenged by all of the artistic books presented in the lab.  We were able to see books which challenged every aspect of the meaning of the page and codex itself.  Books like boundless, which eliminate the possibility of the existence of an observable page, but interestingly enough, there was an ongoing conversation with _Boundless_ with the interaction of such a book that challenges the notion of a page, I would toss and turn and pull on it, interacting in different ways with the book as a page does too with the reader, and I believe there was a conversation with the designer, as he designed and set the stage for the conversation to happen by me picking up the book.
